version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable
      - image: cimg/mysql:8.0

parameters:
  gradle_version:
    type: string
    default: "8.12"

jobs:
  job_b:
    executor: base
    steps:
      - checkout
      - setup_remote_docker
      - run: docker container ls 
      - run: docker network ls
      - run:
          name: docker inspect
          command: |
            for NETWORK_ID in $(docker network ls --filter "driver=bridge" --format "{{.ID}}"); do
                echo "Inspecting network ID: $NETWORK_ID"
                docker network inspect $NETWORK_ID
            done
      - run: docker exec localhost:3306 ls /

workflows:
  workflow-a:
    jobs:
      - job_b
