version: 2.1

workflows:
  testing-oidc:
    jobs:
      - testing-oidc:
          contexts:
            - foo
      
jobs:
  testing-oidc:
    docker:
      - image: cimg/base:current
    resource_class: logan/container-runner
    steps:
      - checkout
      - run: echo $bar




