version: 2.1
orbs: {unicorn: logan/onboarding-orb@0.0.11}
parameters:
  rollback: {type: boolean, default: false}
workflows:
  version: 2
  monitor-qa:
    when: {not: <<pipeline.parameters.rollback>>}
    jobs:
    - logan/hello
