version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable
      - image: cimg/mysql:8.0

parameters:
  gradle_version:
    type: string
    default: "8.12"

jobs:
  job_b:
    executor: base
    steps:
      - checkout
      - setup_remote_docker
      - run: docker container ls 
      - run: docker network ls
      - run: docker exec localhost:3306 ls /

workflows:
  workflow-a:
    jobs:
      - job_b
