version: 2.1

workflows:
  postgresql:
    jobs:
      - postgresql
      
jobs:
  postgresql:
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
          TEST_DATABASE_URL_POSTGRES: postgresql://postgres@localhost/postgres

    # Service container image
      - image: imlogang/postgres-no-pg-cron:latest
        environment:
          POSTGRES_USER: postgres

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE DATABASE test_db; \c test_db; DROP DATABASE test_db;"  



