version: 2.1

workflows:
  postgresql:
    jobs:
      - postgresql
      
jobs:
  postgresql:
    docker:
      - image: cimg/python:3.10
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
          TEST_DATABASE_URL_POSTGRES: postgresql://postgres@localhost/test_db

    # Service container image
      #- image: imlogang/postgres-no-pg-cron:latest
      - image: cimg/postgres:14.9
        environment:
          POSTGRES_USER: postgres

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE DATABASE test_db;" \
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "DROPDATABASE test_db;" \
      - run: | 
          psql \
          -d $TEST_DATABASE_URL_POSTGRES \
          -c "CREATE DATABASE test_db;" \


